version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # Enable Flask auto-reloading
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations  # Persist migrations to host
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Start backend only if DB is ready
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: