"""Add Preference table

Revision ID: 080cbe89c3d1
Revises: 4f5cf2c0fce9
Create Date: 2024-11-04 18:51:34.457439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080cbe89c3d1'
down_revision = '4f5cf2c0fce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='unique_user_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference')
    # ### end Alembic commands ###
